onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/rtr_0/clk
add wave -noupdate /testbench/rtr_0/reset
add wave -noupdate /testbench/rtr_0/router_address
add wave -noupdate /testbench/rtr_0/channel_in_ip
add wave -noupdate /testbench/rtr_0/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_0/channel_out_op
add wave -noupdate /testbench/rtr_0/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_0/error
add wave -noupdate /testbench/rtr_1/router_address
add wave -noupdate /testbench/rtr_1/channel_in_ip
add wave -noupdate /testbench/rtr_1/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_1/channel_out_op
add wave -noupdate /testbench/rtr_1/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_1/error
add wave -noupdate /testbench/rtr_2/router_address
add wave -noupdate /testbench/rtr_2/channel_in_ip
add wave -noupdate /testbench/rtr_2/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_2/channel_out_op
add wave -noupdate /testbench/rtr_2/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_2/error
add wave -noupdate /testbench/rtr_3/router_address
add wave -noupdate /testbench/rtr_3/channel_in_ip
add wave -noupdate /testbench/rtr_3/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_3/channel_out_op
add wave -noupdate /testbench/rtr_3/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_3/error
add wave -noupdate /testbench/rtr_4/router_address
add wave -noupdate /testbench/rtr_4/channel_in_ip
add wave -noupdate /testbench/rtr_4/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_4/channel_out_op
add wave -noupdate /testbench/rtr_4/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_4/error
add wave -noupdate /testbench/rtr_5/router_address
add wave -noupdate /testbench/rtr_5/channel_in_ip
add wave -noupdate /testbench/rtr_5/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_5/channel_out_op
add wave -noupdate /testbench/rtr_5/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_5/error
add wave -noupdate /testbench/rtr_6/router_address
add wave -noupdate /testbench/rtr_6/channel_in_ip
add wave -noupdate /testbench/rtr_6/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_6/channel_out_op
add wave -noupdate /testbench/rtr_6/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_6/error
add wave -noupdate /testbench/rtr_7/router_address
add wave -noupdate /testbench/rtr_7/channel_in_ip
add wave -noupdate /testbench/rtr_7/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_7/channel_out_op
add wave -noupdate /testbench/rtr_7/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_7/error
add wave -noupdate /testbench/rtr_8/router_address
add wave -noupdate /testbench/rtr_8/channel_in_ip
add wave -noupdate /testbench/rtr_8/flow_ctrl_out_ip
add wave -noupdate /testbench/rtr_8/channel_out_op
add wave -noupdate /testbench/rtr_8/flow_ctrl_in_op
add wave -noupdate /testbench/rtr_8/error
add wave -noupdate {/testbench/ips[0]/ps/route_port}
add wave -noupdate {/testbench/ips[0]/ps/data_q}
add wave -noupdate {/testbench/ips[0]/ps/header_info}
add wave -noupdate {/testbench/ips[0]/ps/dest_info}
add wave -noupdate {/testbench/ips[0]/ps/route_op}
add wave -noupdate {/testbench/ips[0]/ps/dest_info_addresses}
add wave -noupdate {/testbench/ips[0]/ps/source_address}
add wave -noupdate {/testbench/ips[0]/ps/curr_dest_addr}
add wave -noupdate {/testbench/ips[0]/ps/random_router_address}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1534 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 245
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {3522 ns}
