// single_port_ram.v

// Generated using ACDS version 23.4 79

`timescale 1 ps / 1 ps
module single_port_ram (
		input  wire [31:0] data,    //    data.datain
		output wire [31:0] q,       //       q.dataout
		input  wire [8:0]  address, // address.address
		input  wire        wren,    //    wren.wren
		input  wire        clock    //   clock.clk
	);

	single_port_ram_ram_1port_2011_otpmvnq ram_1port_0 (
		.data    (data),    //   input,  width = 32,    data.datain
		.q       (q),       //  output,  width = 32,       q.dataout
		.address (address), //   input,   width = 9, address.address
		.wren    (wren),    //   input,   width = 1,    wren.wren
		.clock   (clock)    //   input,   width = 1,   clock.clk
	);

endmodule
